spring:
  datasource:
    username: sa
    password: password
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/camundaDB
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jersey:
    application-path: "/rest"

camunda.bpm:
    history-level: full
    process-engine-name: CamundaProcessEngineConfiguration
    jpa.enabled: true
    authorization:
      enabled: true

